name: "Sync with upstream nixpkgs-unstable"

on:
  schedule:
    - cron: '* */6 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: NixOS
          head: nixpkgs-unstable
          base: everything-ca
          auto_approve: false
